baseURL = '/'
languageCode = 'zh-CN'
title = 'Songline Blog'
summaryLength = 120
hasCJKLanguage = true
enableRobotsTXT = true

[outputs]
home = ['HTML', 'RSS']

[pagination]
pagerSize = 10

[taxonomies]
tag = 'tags'
friend = 'friends'

[markup]
  [markup.highlight]
    noClasses = false
    style = 'github-dark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = true

[params]
description = '记录学习、创作与生活的个人博客。'
